version: '3.2'

services:
  database:
    restart: always
    image: mysql:latest
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    env_file:
      - env/mysql.env
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - mysql-datavolume:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-datavolume:
    driver: local